spring.dotenv.enabled=true

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.jpa.database-platform=${DB_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE}

spring.cloud.config.enabled=${SPRING_CLOUD_CONFIG_ENABLED}

spring.security.jwt.password=${JWT_SECRET}
spring.security.jwt.issuer=${JWT_ISSUER}
spring.security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS}

springdoc.swagger-ui.path=${SWAGGER_PATH}